before_install:
  - wget http://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
  - sudo dpkg -i erlang-solutions_1.0_all.deb
  - sudo apt-get update
  - sudo apt-get install erlang
  - git clone https://github.com/elixir-lang/elixir
  - cd elixir && make && cd ..
before_script: "export PATH=`pwd`/elixir/bin:$PATH"
script: "MIX_ENV=test mix do deps.get, test"
after_success:
  - "mix compile && mix coveralls.travis"
